webp_home:
  path: mdn_webp/home
  methods: [GET,POST]
  defaults:
    _controller: 'MdnWebp\Controller\GenerateController::showConfigPage'
webp_product:
  path: mdn_webp/generate/product/{product}
  methods: [GET,POST]
  defaults:
    _controller: 'MdnWebp\Controller\GenerateController::generateProductImage'